name: Sync Upstream
on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync from Codeberg
        run: |
          git remote add upstream https://codeberg.org/ziglings/exercises.git
          git fetch upstream main --tags
          git checkout main
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git merge upstream/main --allow-unrelated-histories
          git push origin main --tags
